# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/testing',
                'doc_host': 'https://Vipulc659.github.io',
                'git_url': 'https://github.com/Vipulc659/testing',
                'lib_path': 'testing'},
  'syms': {'testing.core': {'testing.core.foo': ('core.html#foo', 'testing/core.py')}}}
